### ISSUE TITLE
Add contribution and build sections to the readme

### ISSUE THREAD

**Issue by sclarke81** [meziantou/Meziantou.Framework#10]
I think it'd be helpful to add some info to the readme about setting up your build environment and any guidance you want to provide to potential contributors. I think it lowers the barrier to getting set up and makes it more likely for people to contribute.

**Comment by meziantou** [comment]
Hi,
I didn't expect lots of people to contribute, but I'm very happy to get the first external contribution!
I'll add some a contribution guide.

**Comment by sclarke81** [comment]
That's great. It's nice to be able to help out. The SourceLink stuff worked nicely by the way.

I partly mentioned setting up the environment because I found out that having the SDK version specified in the `global.json` means that you have to have that specific version. So you need to have 2.1.302 (I had 2.2.101 and it didn't work).

I'm not sure if you need to have it pinned to a specific version of the SDK? If so you could provide a download link. If not maybe the `global.json` could be removed?

**Comment by sclarke81** [comment]
Ah, I see. That makes sense.
