### ISSUE TITLE
Exclude code from test coverage and code analysis in StronglyTypedId

### ISSUE THREAD

**Issue by ChrisTorng** [meziantou/Meziantou.Framework#180]
I just start to use StronglytypeId. Found the test coverage result includes all the generated codes. According to [Exclude code from test coverage and code analysis](https://theroks.com/exclude-code-from-test-coverage-and-code-analysis/), I hope the generated code can include `[DebuggerNonUserCode]` to hide from test coverage and stepped into while debugging. My other issue [Other ways to support exclude from code analysis?](https://github.com/manuelroemer/Nullable/issues/6) may help?

**Comment by meziantou** [comment]
Thanks for your feedback!

I'm not sure what is the best strategy here. I do understand why you would like to remove this code from code coverage. At the same time the generated code is part of your codebase. So, I'm not sure what is the best way to deal with that. Maybe I can just add an option to add the `DebuggerNonUserCode` attribute to all generated properties / methods.

Which tool do you use for code coverage?

**Comment by ChrisTorng** [comment]
I know it's base on `partial` keyword. But I don't think it's part of my code. I tend to believe anything it generated, so not willing to add test or debug into it. If I need to check, I will open the generated .g.cs file to check. If I need to debug into, I will turn off "Enable Just My Code". So for me, I hope the attribute is generated by default, not opt-in.

I use the Visual Studio 2019 build in Code Coverage tool.

**Comment by meziantou** [comment]
The next version will add the `System.CodeDom.Compiler.GeneratedCodeAttribute` to the generated members by default. This attribute seems to be excluded from code coverage or at least you should be able to configure your tool to exclude this attribute.
