### ISSUE TITLE
Easier to inherit from StronglyTypedId class by changing private to protected

### ISSUE THREAD

**Issue by ChrisTorng** [meziantou/Meziantou.Framework#182]
I hope to inherit from a StronglyTypedId class. Currently the base constructor is `private`, so I can't write `: base(value)` in the derived class. I know I can write my own `protected` base constructor to overcome this. But still think it should be better for the generated class to have `protected` by default.

The same problem to other private members like `_value`, `TypeConverter`, `JsonConverter`... `protected` should be better for derived class to change the default behavior, not necessary write my own one.

**Comment by meziantou** [comment]
The ctor could be protected for a non-sealed class. However I'm not sure to understand your use-case

- why do you want to access `_value` in a derived class instead of `Value`?
- why do you want the converters to be protected?

**Comment by ChrisTorng** [comment]
I have a domain service, that uses an Id. It needs to support some different backend services. They use different Ids. One is made by me, using `GUID`. Others are third parties. One of them is `Int16`, it will reuse previous used Id. But I needs a global unique Id (to store to DB PK field). So I'm considering to use other fields to make it unique. Maybe a self generated `GUID`, or by other information like timestamp. I needs to combine some fields to make it a real unique Id.

So I have an `abstract` base `string` Id class, and a derived Id class to receive a `GUID`. Another derived Id class to receive `Int16` with other fields. They will generate a `string` Id that has a prefix to note the real backend Id class, with other fields combined into a `string`. Use the combined `string` as the base class's `string` Id.

(Currently `abstract` Id class is not possible, that is another issue. I'm thinking of write everything by me, not using StrongTypedId anymore.)

So the converter needs to read the prefix, to create the right derived class, that can validate and extract all the fields in the base `string` Id.

Access to `_value` from derived class is not necessary. Maybe someone hope to access it directly to get a little performance gain.

**Comment by meziantou** [comment]
This seems to be very custom, so I'm not sure that the StronglyTypedId generator is the right solution here.

note: The ctor is now `protected` so you can create inherited classes.

> Access to _value from derived class is not necessary. Maybe someone hope to access it directly to get a little performance gain.

The JIT should inline the property, so it should not impact the performance.

**Comment by ChrisTorng** [comment]
Sorry for late response.

While trying StronglyTypedId, the latest VS2019 shows "Feature 'CodeLens references' is currently unavailable due to an internal error." frequently, very annoying.

The Live Unit Testing is not working, failed by "error CS0616: 'StronglyTypedId' is not an attribute class" with other similar errors.

And I don't like the extra `ValueAsString`, `FromString()`, `ToString()`, `Parse()`, `TryParse()`. Think they are useless in `string` StronglyTypedId.

I've gived up using StronglyTypedId. I've tried `record`, gived up too. Now I'm trying [CSharpFunctionalExtensions](https://github.com/vkhorikov/CSharpFunctionalExtensions)'s [`SimpleValueObject<string>`](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/master/CSharpFunctionalExtensions/ValueObject/SimpleValueObject.cs). And use some StronglyTypedId's generated code as my template.

One more thing to mention. On [C# 9 records as strongly-typed ids - Part 5: final bits and conclusion](https://thomaslevesque.com/2021/03/19/csharp-9-records-as-strongly-typed-ids-part-5-final-bits-and-conclusion/), there is a comment mentioned Swashbuckle support with `StronglyTypedIdSchemaFilter` class, that you may consider to adopt.
