### ISSUE TITLE
Natural Sort and Stable Sort don't seem to work on ConcurrentObservableCollection

### ISSUE THREAD

**Issue by heavywoody** [meziantou/Meziantou.Framework#206]
I love everything about the collection, but I noticed in binding to a datagrid, the Natural Sort and I think the Stable Sort aren't working as expected.  Let me explain in case you don't use the terms.

Let's say we have a datagrid with two columns that are strings and these values:

Name          Value
Quarter1       1
Quarter1        240
Quarter1       11
Quarter1        2
Quarter1        Unemployed

In a Natural Sort, if I clicked on Value to sort, I would expect the sort to be as below, since the numbers would be treated as numbers, even thought they are a string.
Name          Value
Quarter1       1
Quarter1       2
Quarter1       11
Quarter1        240
Quarter1        Unemployed

Ok, on a Stable Sort, it just means values that are the same would keep their order.  So if I now clicked on Name to sort, since they all have the value on Quarter1, nothing should change.  But without Stable Sorting, sometimes the rows will re-arrange.

Using OrderBy does provide a Stable Sort.  And to get a Natural Sort, I often use the IComparer:

[SuppressUnmanagedCodeSecurity]
        internal static class SafeNativeMethods
        {
            [DllImport("shlwapi.dll", CharSet = CharSet.Unicode)]
            public static extern int StrCmpLogicalW(string psz1, string psz2);
        }
        public class NaturalSortGeneric : System.Collections.Generic.IComparer<string>
        {

            public int Compare(string x, string y)
            {
                return SafeNativeMethods.StrCmpLogicalW(x ?? "", y ?? "");
            }
        }

So if one would do something along the lines of _observablecollection=_items.OrderBy(x=>x.Name,new NaturalSortGeneric()), that would actually provide a Stable and Natural Sort.  But I have no idea how to implement that with your setup.  What is important about Stable Sort is your don't want the underlining datasource to keep changing order, so that is what attracted me to your control.  It would seem _items never changes, which is perfect to use that as a source for _observablecollection that you have.  While you are at it, having a AddRange and DeleteRange with only one notification would be fantastic!

**Comment by meziantou** [comment]
There are 2 ways to answer your question:
- If you want to sort data in the UI, you can use WPF functions to sort data (`ListCollectionView` and its `CustomSort` property ): <http://web.archive.org/web/20120205143541/http://bea.stollnitz.com/blog/?p=24>
- If you want to sort the collection from the code (not for the UI), the collection doesn't provide any good solution. You can sort items by removing/inserting items. We could add a new `Sort` method if needed.

**Comment by meziantou** [comment]
I've added a `Sort` method in the version 1.5.0. This method sorts the collection and raise a Reset event.

**Comment by heavywoody** [comment]
Thank you. I wanted to mention that I was using ListCollectionView in the past before I looked at your solution.  It has neither stable or natural sort.

**Comment by heavywoody** [comment]
Thats fantastic. I will have a look.  Thanks for the quick turn around. I was going to write something but I just wasn't sure how to make it work inside the code.

**Comment by heavywoody** [comment]
I went ahead and got the latest version and tried it out.  At least the way I am using it, Natural Sort now works great.  But Stable Sort doesn't work.  And maybe that is something you have other things you would rather get in first.  But if you do address this, please let me know.  I think the reason why might be you changed the order of both _items and _observablecollection, so you lose the original sort order.  If you could sort only the _observablecollection and preserve leave _items alone, I think it would would. Or utilize OrderBy, which always makes the return Stable.  But let me give you an example of what I mean. In the first picture, I am sorting by name and all the Values are "0".  So in a Stable Sort, I would expect if I click on Value to sort, nothing should happen, because all the values are the same so rows should not rearrange. But notice they do.
![SortAfter](https://user-images.githubusercontent.com/9383906/121992316-a394f400-cd5e-11eb-9355-3b769d8b50b5.PNG)
![BeforeSort](https://user-images.githubusercontent.com/9383906/121992319-a42d8a80-cd5e-11eb-81d7-4d7da46c9d9c.PNG)

I will tell you a way to show a stable sort very quickly. Make two ObservableCollections A and B.  Bind A to a datagrid. When the grid sorts, have logic like A=new ObservableCollection<SomeObject>(B.orderby(x=>x.Name) and you will notice if values are the same it won't change the order.  But if you use on ObservableCollection on it's own, it won't work because the underling collection is being changed each time.  So I think if you could do something like   _observablecollection=new DispatchedObservableCollection(_items.Orderby(x=>x.Name), it would preserve the _items order by then the _observablecollection should have stable sort.   Probably too much information, but it is hard to find a collection that does both Natural and Stable and is thread safe like what you have, just throwing it out there if you wish to do something like that.

**Comment by meziantou** [comment]
I've added a new method named `StableSort`. It should be a little bit slower and less memory efficient as it uses `OrderBy`, but it should fit your need.

**Comment by heavywoody** [comment]
Wow, thank you so much!  I was really surprised at how quickly you respond and add features asked for.  That is tremendous.  I added a method to AddRange but wondering if you had a way to do it already that I missed?

**Comment by meziantou** [comment]
I don't think there is an AddRange method. You can submit a PR if you want.
