### ISSUE TITLE
Make Meziantou.Framework.FastEnumToStringGenerator generate code with public accessibility

### ISSUE THREAD

**Issue by mattmckinstry** [meziantou/Meziantou.Framework#211]
Currently generates internal extention methods which arent much use if you have a shared assembly containing your Enums.

Perhaps it could read the accessibility level from the Enum

**Comment by meziantou** [comment]
The version 1.0.2 should fix this issue. By default, it detects the type visibility. You can force the method to be internal by setting `IsPublic = false`. You can also change the namespace for the generated extension methods.

````c#
[assembly: FastEnumToStringAttribute(typeof(Sample.Color), IsPublic = true, ExtensionMethodNamespace = "Sample.Extensions")]
````

**Comment by mattmckinstry** [comment]
This is excellent, thanks

**Comment by mattmckinstry** [comment]
@meziantou do the new properties need exposed on the Attribute constructor?

**Comment by meziantou** [comment]
The attribute is provided by the source generator. If you use the latest package version, the new attribute properties should be accessible as in the provided example.
