### ISSUE TITLE
Make ConcurrentObservableCollection<T> Implementation simple

### ISSUE THREAD

**Issue by Ghislain1** [meziantou/Meziantou.Framework#225]
Why do you not use BindingOperations.EnableCollectionSynchronization by extended Observablecollection <T>?
https://docs.microsoft.com/de-de/dotnet/api/system.windows.data.bindingoperations.enablecollectionsynchronization?view=net-5.0

**Comment by meziantou** [comment]
- `BindingOperations.EnableCollectionSynchronization` is only available in WPF, whereas the collection could be used in other contexts. I know this is in the namespace Meziantou.Framework.WPF but in fact there is no requirements for WPF.
- It requires the user to not forget to call `BindingOperations.EnableCollectionSynchronization` on the UI thread with the right lock object (the same you will use to add or remove items). This also means your UI thread will block operations on the list while refreshing the UI. The `ConcurrentObservableCollection<T>` requires to bind the right collection, but I think this is easier and it doesn't block the collection while refreshing the UI.
