### ISSUE TITLE
ConcurrentObservableCollection<T>  not serializable and not .NET Standard 2.1 compliant

### ISSUE THREAD

**Issue by Gerardo-Sista** [meziantou/Meziantou.Framework#226]
**First of all thank you** for this "ready to go" awesome Collection.
Two problems: 
ConcurrentObservableCollection<T>  **is not serializable** with .NET json . Can you add support for this?,
Also can you remove the (confusing) "WPF" word (WPF in not required!!) and refactor to **fully target .NET standard 2.1**? 

Consider create a new Nuget Package "Meziantou.ConcurrentObservableCollection"  with only this collection (but targeting .NET std 2.1 and serializable as said before) because is really useful!

Thank you :)

**Comment by meziantou** [comment]
> ConcurrentObservableCollection is not serializable with .NET json . Can you add support for this?,

I've made a fix to support json deserialization https://github.com/meziantou/Meziantou.Framework/commit/525f2be1a379f6a48541724d30e14c10080908f0

> Also can you remove the (confusing) "WPF" word (WPF in not required!!) 

That would be a breaking change. I understand this is not the best namespace, but does it prevent you from using the collection?

> fully target .NET standard 2.1

It currently targets .NET 4.6.1 and .NET Core 3.1+. Why do you need .NET Standard 2.1?

**Comment by Gerardo-Sista** [comment]
Hello, thank you for your quick support.
 - I'll test later serialzation/serialization support. Thank you!
 - No it doesn't prevent it from using, but is really confusing since it "suggests" that WPF is necessary.
 - Why .NET Standard 2.1? For full multiplatform/portability. I have multiple class library targeting .NET standard 2.1 and I can use them in WPF, WinForm, ASP, UWP, Xamarin etc etc. without problems. .NET Standard is the best (and lowest) target platform to avoid compatibility problems. .NET core is good, .NET standard has less power but far better compatibility. Almost all general-purpose Nuget Packages target .NET Standard.

**Comment by meziantou** [comment]
> No it doesn't prevent it from using, but is really confusing since it "suggests" that WPF is necessary.

Ok, so I prefer keeping it as-is to prevent breaking changes. I know a few projects that use this collection, so I don't want to break them.

> For full multiplatform/portability

The new standard is .NET 5 (which is targeted by the lib) https://devblogs.microsoft.com/dotnet/the-future-of-net-standard/.
Unless there is a compatibility issue with a specific target, I do not plan to add another target.

**Comment by Gerardo-Sista** [comment]
Well, 
your considerations are ok, but will need more time until .NET standard "dies".

However thank you again for your very good collection and thanks also for made it serializable, wihic is a great improvement.
 
 :)
