### ISSUE TITLE
[Question] [Not a bug] It appears this is cross platform, is this true?

### ISSUE THREAD

**Issue by jeffward01** [meziantou/Meziantou.Framework#229]
Hello!

**My question is specifically about the  [FullPath library](https://github.com/meziantou/Meziantou.Framework/tree/main/src/Meziantou.Framework.FullPath) you developed.**

-------

FANTASTIC library! This is excellent! I am surprised that there are not more of these 'strongly typed' path libraries, I am sure it is because as you say, Path's are hard.

I would like to take your library a step further and use classes such as:

`AbsoluteFileName`
`AbsoluteDirectory`
`RelativeFileName`
`etc`

I have been playing around with this library here: https://github.com/danyx23/smartpath which is also very cool.  The issue with the "[Smart Path](https://github.com/danyx23/smartpath)" library is that it is 'Windows only" paths and is not compatible with unix paths.  

As dotnet core is very cross platform now, the windows only limitation is a large one.  I would like to use your library as the 'core' of a version of [SmartPath ](https://github.com/danyx23/smartpath) 2.0. 

Questions

1.)  Based on 30 second assesment, is this possible? Will I hit any limitations with the [FullPath library](https://github.com/meziantou/Meziantou.Framework/tree/main/src/Meziantou.Framework.FullPath) you developed?

2.) Is there a reason why you did not break out your `FullPath` class to F`ileName` and `Directory` as they have done at Microsoft and also in the [SmartPath ](https://github.com/danyx23/smartpath) library? I am just curious.

-------
-------

_Note: I have been diving deep on your materials for the past few weeks. VERY COOL! you are an invaluable resource to the dotnet community! Thank you for everything! I have learned alot from you in this short time._

**Comment by meziantou** [comment]
FullPath supports the _current_ OS paths (`/` or `\`). Under the hood, it relies on System.IO.* APIs. For SymLink resolution it support Windows and Unix. For path equality, it is case-sensitive on Unix and case-insensitive on Windows. You can override the behavior using the `ignoreCase` parameter

> 2.) Is there a reason why you did not break out your FullPath class to FileName and Directory as they have done at Microsoft and also in the SmartPath library? I am just curious.

I don't see the need for it. But if there is a useful use-case, why not.
