### ISSUE TITLE
Filter ConcurrentObservabeableCollection internally

### ISSUE THREAD

**Issue by heavywoody** [meziantou/Meziantou.Framework#232]
Wondering if this possible.  Your ConcurrentObserveableCollection with the AddRange works SO WELL that the Filter on a DataGrid can't keep up with it.  I am able to add/update thousands of records per second now, but reapplying the filter on the grid isn't practical.

So let me ask you this. It is possible to add a method to that the ObserveableCollection portion is filtered and updated when any changes happen.  Basically, a way to get a subset of the data but if data comes in after you do a query, any new records are made part of the subset as well?

Because right now if I use a Telerik RadGridView and set a filter, when the thousands of records come in, most are being ignored by the filter.  Not feasible to reapply filter every second. Any thoughts?

**Comment by meziantou** [comment]
> Your ConcurrentObserveableCollection with the AddRange works SO WELL that the Filter on a DataGrid can't keep up with it

Good to hear the bottleneck is not the collection :)

- Doesn't Telerik provide a native way to filter collection?
- I think adding filtering into the collection would add much complexity and I'm not sure there is a need for it. Why can't you do it yourself by maintaining 2 collections (all data and filtered data). Another solution is to create a `FilteredObservableCollection` which should look like:
  
    ````
    class FilteredObservableCollection<T> : ICollectionObservable
    {
        private List<T> _items = new List<T>();
    
        public FilteredObservableCollection(ICollectionObservable collection, Func<T, bool> predicate)
        {
            collection.CollectionChanged += OnCollectionChanged;
        }
    
        private void OnCollectionChanged(object sender, CollectionChangedEventArgs e)
        {
            // switch e.ChangeType
            // use "predicate" to filter new items data and use AddRange to fill "_list"
        }
    }
    ````

**Comment by heavywoody** [comment]
With Telerik WPF RadGridView, you can create FilterDescriptors and apply to a collection. The problem I am running into is new records aren't showing in the Filter.  So if I set a filter to give me everything with Name.Contains("blue"), and I get 2000 new records that contain "blue", they don't appear in the filtered grid.  In reading their documentation, it purposeful for performance.  I couldn't remember offhand if creating an observeablecollection from another would still update items changed?

On another note, not sure if you got a chance to look at my suggested implimentation of AddRange? I just put it in a comment last week. But WOW is it fast!

**Comment by meziantou** [comment]
> On another note, not sure if you got a chance to look at my suggested implimentation of AddRange? I just put it in a comment last week. But WOW is it fast!

The AddRange method has been added and is available in the latest version as mentioned in this comment: https://github.com/meziantou/Meziantou.Framework/issues/230#issuecomment-888698744

**Comment by meziantou** [comment]
If I well understand your issue, you want the datagrid to show new items whatever the current filters. This seems very specific, so I'm not sure how it can fit into the collection.

**Comment by heavywoody** [comment]
Sure, that is why I considered either making an internal filtered collection so that I can ignore the filter on the datagrid.  If I could pass to the ConcurrentObserveableCollection criteria, I would assume it would always be in sync so that new items are added they would flow to the filtered collection. But I am trying your suggestion of maintaining two collections see if that works.
