### ISSUE TITLE
InputSelectEnum  example that uses the onchange event?

### ISSUE THREAD

**Issue by JohnMarsing** [meziantou/Meziantou.Framework#233]
I have been using your InputSelectEnum blazor component for a Blazor Server app and was wondering if you had an example that uses the onchange event?

Here's how I'm using it inside an <EditForm> </EditForm> tag

<InputSelectEnum @bind-Value="Registration.LocationEnum"
class="form-control" />
<ValidationMessage For="@(() => Registration.LocationEnum)" />

Depending on the enum value, I want to hide another control I have on the same form Registration.CampTypeEnum

I'm using your control here...

https://github.com/livingmessiah/LivingMessiahBlazor/blob/master/LivingMessiah.Web/Pages/Sukkot/CreateEdit.razor

Thanks,
John

**Comment by meziantou** [comment]
Hi,

If you really want to use the onchange event, you need to _expand_ the bind directive:

````razor
<InputEnumSelect Value="@model.Value" ValueExpression="() => model.Value" ValueChanged="EventCallback.Factory.Create(this, RuntimeHelpers.CreateInferredEventCallback(this, OnValueChanged, model.Value))" />

@code{
    void OnValueChanged(MyEnum newValue)
    {
        Registration.LocationEnum = newValue;
        // hide/show controls here
    }
}
````

A much simpler way to do it is to have a computed property. This works as Blazor calls `StateHasChanged` after an event handler (`ValueChanged` set using the `@bind` directive)

````razor
<InputSelectEnum @bind-Value="Registration.LocationEnum" class="form-control" />

@if (CanEditOtherField)
{
    <InputSelectEnum @bind-Value="Registration.MyOtherProperty" />
}

@code {
     bool CanEditOtherField => Registration.LocationEnum == Location.Value;
}
````
