### ISSUE TITLE
Possible to add a RemoveRange?

### ISSUE THREAD

**Issue by heavywoody** [meziantou/Meziantou.Framework#249]
I love the AddRange you added with setting the flag. Would it be hard to add a RemoveRange using same functionality?

**Comment by meziantou** [comment]
`RemoveRange` is more complex to implement as `ImmutableList.RemoveRange` doesn't tell you which items are removed. So, it's harder to synchronize the change with the observable collection. It's not impossible, just require more work.

**Comment by meziantou** [comment]
Also, you cannot send a single CollectionChanged event unless all removed items are sequential. So, the only benefit is to improve the performance of the operation on the ImmutableList and the List (in the observable collection)

**Comment by heavywoody** [comment]
Yeah, that makes sense.  The Add is very fast but the Remove is much slower.  So just trying to figure out how to speed it up.  i did a stopwatch on add and remove and you can see a big difference.  Any suggestions on how to remove items faster?

Add Time elapsed: 00:00:00.0000058
Add Time elapsed: 00:00:00.0000043
Add Time elapsed: 00:00:00.0000036
Add Time elapsed: 00:00:00.0000030
Add Time elapsed: 00:00:00.0000052
Add Time elapsed: 00:00:00.0000035
Add Time elapsed: 00:00:00.0000050
Add Time elapsed: 00:00:00.0000034
Add Time elapsed: 00:00:00.0000037
Add Time elapsed: 00:00:00.0000033
Add Time elapsed: 00:00:00.0000036
Add Time elapsed: 00:00:00.0000034
Add Time elapsed: 00:00:00.0000038
Add Time elapsed: 00:00:00.0000039
Add Time elapsed: 00:00:00.0000035
Add Time elapsed: 00:00:00.0000036
Add Time elapsed: 00:00:00.0000039
Delete Time elapsed: 00:00:00.0369475
Delete Time elapsed: 00:00:00.0307946
Delete Time elapsed: 00:00:00.0422107
Delete Time elapsed: 00:00:00.0388697
Delete Time elapsed: 00:00:00.0321582
Delete Time elapsed: 00:00:00.0340374
Delete Time elapsed: 00:00:00.0399094
Delete Time elapsed: 00:00:00.0341092
Delete Time elapsed: 00:00:00.0350533
Delete Time elapsed: 00:00:00.0306140
Delete Time elapsed: 00:00:00.0480949
Delete Time elapsed: 00:00:00.0329956
Delete Time elapsed: 00:00:00.0400017
Delete Time elapsed: 00:00:00.0369567
Delete Time elapsed: 00:00:00.0407502
Delete Time elapsed: 00:00:00.0456813
Delete Time elapsed: 00:00:00.0458296
Delete Time elapsed: 00:00:00.0311056
Delete Time elapsed: 00:00:00.0432627

**Comment by meziantou** [comment]
Could you share the code of your benchmark. How do you remove items? `Remove`, `RemoveAt`? I expect `Remove` to be slower than `RemoveAt`, and of course much more slower than adding items. Indeed, you first need to find the item you want to remove in the collection before removing it.

**Comment by heavywoody** [comment]
Sure, I am just checking to see if the value is in a dictionary. If so i delete it. If not, I add it.  But the deleting is taking so much longer where the adding I can add thousands of records in seconds.

if (control.HasFlag(StatControl.Removed))
                        {
                            ClientStat outStat;
                            if (_dictStats.TryGetValue(name, out outStat))
                            {
                                _dictStats.Remove(name);
                                Stopwatch sw = new Stopwatch();
                                sw.Start();
                                ClientStats.Remove(outStat);
                                sw.Stop();
                                Console.WriteLine("Delete Time elapsed: {0}", sw.Elapsed);
                            }
                            else
                            {
                                Stopwatch sw = new Stopwatch();
                                sw.Start();
                                ClientStats.Add(outStat);
                                sw.Stop();
                                Console.WriteLine("Add Time elapsed: {0}", sw.Elapsed);
                            }


                            return;
                        }

**Comment by meziantou** [comment]
> But the deleting is taking so much longer where the adding I can add thousands of records in seconds.

This is expected. Adding items is fast, you just need to add new items at the end of the collection. Removing item from the collection is O(n) as you need to find the element in the collection before removing it. So, if the collection contains lots of items, it will take time to find it. `RemoveAt` should be O(1) as it needs to remove the item without searching for it first.

How many items does the collection contain?

**Comment by heavywoody** [comment]
It can have between 20k and 2 million records.  That is why I was really happy when you added the AddRange because then I was adding thousands of records every second, but the delete is so much longer.  So I am trying to figure out a work around to delete faster.  Another internal dictionary.  Something.  Thanks!
