### ISSUE TITLE
CredentialManager there in Win32 throwing Null Exception.

### ISSUE THREAD

**Issue by vedeevi** [meziantou/Meziantou.Framework#32]
Win32.CredentialManager is currently throwing following exception when trying to access the code in following way...

`public static async Task GetCredential()
{
            var credentials = CredentialManager.EnumerateCrendentials();
            foreach(var credential in credentials)
            {
                Console.WriteLine($"{credential.UserName}");
            }
}`

((System.ArgumentException)ex).Message
"Value cannot be null. Parameter name: ptr"

**Comment by meziantou** [comment]
Thanks for reporting the issue! It should be fix in the version 1.3.5 (published in a few minutes)
