### ISSUE TITLE
FullPath: [Feature] Get path without any symbolic links inside

### ISSUE THREAD

**Issue by inelisoni** [meziantou/Meziantou.Framework#370]
TryGetSymbolicLinkTarget returns a real path only if a final path is a symbolik link (e.g. _/app/log_ is a link to _/var/log/app_). This doesn't work for a path like _/app/log/raw_.

I write some code (draft) to do this.

```
static FullPath GetRealPath(FullPath path)
{
    var currentPath = path;
    var relativePath = "";
    while (!currentPath.IsEmpty)
    {
        while (currentPath.TryGetSymbolicLinkTarget(out var realPath))
            currentPath = realPath.GetValueOrDefault();
        var name = currentPath.Name;
        if (string.IsNullOrEmpty(name)) // Name is empty for root path (e.g. /).
            name = currentPath;
        relativePath = Path.Combine(name, relativePath);
        currentPath = currentPath.Parent;
    }
    return FullPath.FromPath(relativePath);
}
```

**Comment by meziantou** [comment]
I'm not sure to fully understand your use case. Could you share a list of commands (`touch ...`, `ln ...`, etc.) to create the files and symlinks. Also, the expected result for `GetRealPath(path)`?

**Comment by inelisoni** [comment]
Expected behavior is to do not have any symlinks in path.
```
mkdir ~/app
ln -s -T / ~/app/root_drive
GetRealPath("~/app/root_drive/var/log") => /var/log
```

**Comment by meziantou** [comment]
I don't know what the correct signature for the method should be. Here's a draft, but I don't like the new boolean parameter: https://github.com/meziantou/Meziantou.Framework/pull/371/files#diff-5d24294ef27966fb5c39ec92bc5d774176ab711518c243d5436e72fdcb612691R265

**Comment by inelisoni** [comment]
Maybe, `RemoveSymbolicLinks`?

**Comment by meziantou** [comment]
```
FullPath path;
path.TryGetSymbolicLinkTarget(SymbolicLinkResolutionMode.AllSymbolicLinks, out var resolved);
```
