### ISSUE TITLE
Option to add Implicit Conversion from string to StronglyTypedId

### ISSUE THREAD

**Issue by kcadduk** [meziantou/Meziantou.Framework#427]
Brilliant Repo btw. Great Ideas.

I'm happy to have a pop at this myself, but I wanted to check.

Have you considered the ability to implicitly convert from things like string to a FooId which is an underlying string type? Saves having to `public FooId FooId {get;} = new FooId(Nanoid.Generate())`, I can instead `public FooId FooId {get;} = Nanoid.Generate()`

It should be easier in my mind to get into a FooId, but then have the type safety once there

**Comment by meziantou** [comment]
Hi,

I considered it but it reduces safety. For instance, `FooIdInstance == 1` (typed on the left, not typed on the right) is valid as it will use the implicit converter for the right member.

An explicit converter is safer, but I'm not sure this improves the usability of the code. I'm open to feedback.

If you think implicit converters are important, this could be an option in the attribute ctor:

````c#
[StronglyTypedId(typeof(int), generateImplicitConverter: true)]
````

**Comment by kaddyuk** [comment]
`FooIdInstance == 1` would only be valid if FooIdInstance was `typeof(int)`, Again, I have to type `FooIdInstance = new FooIdInstance(1)`, I think the (slight) loss in safety is worth the improvement in readability. Just my 2c.

I can agree with the `generateImplicitConverter` argument.

I'll leave this up for a short while, its not working, if other readers could +1 if they agree? Or not, happy to listen to feedback.

Thanks
Kevin
