### ISSUE TITLE
Have a FooId.Empty static property on the struct to generate an empty ID

### ISSUE THREAD

**Issue by kaddyuk** [meziantou/Meziantou.Framework#428]
During testing, when I want to test a method that requires a FooId parameter, when the value of the FooId doesn't actually matter, I have to call `MethodUnderTest(new FooId())`

I would like to have the syntax `MethodUnderTest(FooId.Empty)` to improve readability. Might only be able to provide the property on the main value types (string, int, bool, char, Guid, ObjectId) but those types will cover a lot of use cases for a lot of users.

Happy to open a PR for this if not already declined.

**Comment by meziantou** [comment]
Have you considered using `MethodUnderTest(default)`?

**Comment by kaddyuk** [comment]
That returns null for `typeof(string)`, the Empty property would allow it to be `string.Empty`

Potentially splitting hairs, but it is a concern.

**Comment by meziantou** [comment]
I'm not sure everybody would agree on what `Empty` should return, so I don't know if this is a good idea to generate it.

Note that you can create the property yourself using the existing code:

```c#
[StronglyTypedId(typeof(string))]
partial struct FooId
{
    public static FooId Empty => new("");
}
```
