### ISSUE TITLE
How to use it with List<T> and pagination

### ISSUE THREAD

**Issue by bojankostic81** [meziantou/Meziantou.Framework#441]
I'm trying to implement your Blazor infinite scroll component with my response from API which returns PaginationResponse.

```
public class PagingResponse<T> where T : class
{
    public List<T> Items { get; set; }
    public MetaData MetaData { get; set; }
} 

public class MetaData
{
    public int CurrentPage { get; set; }
    public int TotalPages { get; set; }
    public int PageSize { get; set; }
    public int TotalCount { get; set; }
    public bool HasPrevious => CurrentPage > 1;
    public bool HasNext => CurrentPage < TotalPages;
}
```

I have tested provided example and it works great, however, I'm having difficulties combining it with my response type which should act like pagination. The problem is that I do not know how to identify when the user scrolled to a new page in order to fetch new page data from API. Can you provide some assistance?

**Comment by meziantou** [comment]
When a user scrolls to a new page, the `ItemsProvider` delegate is called with a `StartIndex`. So, you can know which page to load (PageIndex = StartIndex / PageSize). I've added a sample to the project https://github.com/meziantou/Meziantou.Framework/commit/175366e385887bc0a02aacba03d49d221b9432fa

**Comment by bojankostic81** [comment]
Thanks for the provided example, it works like a charm. However, I have stumbled on a few issues. 

1. In my project I have a page with three states: load - while data is fetching from API; empty - API call is finished but there is no data; collection: data is fetched from API and user can scroll. Is there a way to do this with your infinite scroll component?

2. I have a search option on this page which is triggered after user enters at least 3 characters. Is there a way to reinitialize the infinite scroll component, because now when I type the text for search, fetching items are triggered on scroll, but the component gets in an infinite loop and it is not rendering data?

```
@page "/test"
@layout MainLayout
@inherits CustomComponent
@using MytyPro.B2B.Components.Client
@inject IClientService clientService
@inject IJSRuntime JS

<div id="main-content">
	<Loader /> -- show loader while page is loading (data is fetching from API)
	<Placeholder /> -- after data is fetched, if DataSource is null show placeholder
	<div class="page-content">
		<div id="clients-list">
			<div class="page-content">
				<Search Placeholder="Search..." OnValueChanged="SearchAsync" />
				<ul id="clients-wrap">
					<InfiniteScrolling ItemsProvider="GetItems">
						<ItemTemplate Context="item">
							<ClientItem Item=@item />
						</ItemTemplate>
						<LoadingTemplate>
							@if (MetaData?.HasNext == true)
							{
							<div><span class="oi oi-reload spin"></span> Loading more items...</div>
							}
					</LoadingTemplate>
				</InfiniteScrolling>
			</ul>
		</div>
	</div>
</div>
</div>

@code {
    private UserViewModel CurrentUser { get; set; }
    public QueryParameters QueryParameters { get; set; }

    [Parameter]
    public IEnumerable<ClientViewModel> DataSource { get; set; }
    private MetaData MetaData { get; set; }

    protected override async Task OnInitializedAsync()
    {
        CurrentUser = await GetCurrentUserAsync();
        QueryParameters = new QueryParameters(CurrentUser.AccountId);
    }

    async Task<IEnumerable<ClientViewModel>> GetItems(InfiniteScrollingItemsProviderRequest request)
    {
        const int PageSize = 10;
        var pageIndex = request.StartIndex / PageSize;
        QueryParameters.PageSize = PageSize;
        QueryParameters.PageNumber = pageIndex + 1;

        var response = await clientService.GetAllAsync(QueryParameters);
        DataSource = response.Items;
        MetaData = response.MetaData;
        return DataSource;
    }


    public async Task SearchAsync(string text)
    {
        if (text.Length >= 3)
        {
            Console.WriteLine(text);
            QueryParameters.SearchCriteria = text;
        }
    }
}

```

**Comment by meziantou** [comment]
I've added a sample for your second point https://github.com/meziantou/Meziantou.Framework/commit/5ca8395b87e71b2e6813f1ddb3ec69fc389fa994

I'm not sure to understand the first point. There is a `LoadingTemplate` available. Do you need something else?

**Comment by bojankostic81** [comment]
Thanks a lot for your reply and example. Everything works fine now. I have one more question, is there a possibility to call GetItems in the OnInitializedAsync method?

**Comment by meziantou** [comment]
This is not possible. However, you can start loading the first page of data, and make the `GetItems` implementation return the cached data on the first call.

**Comment by bojankostic81** [comment]
Thanks, Is there a way to force stop loading more items? For example on the 5th page, I have detected an item that fulfills some conditions, I would like to stop further scrolling, but without disposing of the component because the user can enter a different condition for detecting an item.

**Comment by meziantou** [comment]
> Is there a way to force stop loading more items?

Make the `GetItems` method return an empty collection
