### ISSUE TITLE
New Feature! 

### ISSUE THREAD

**Issue by marceloruilova** [meziantou/Meziantou.Framework#469]
-A description of the issue
I am working with your GenericFormField and I have a byte field which is not supported by blazor InputNumber, without using GenericForm component we used to add a casting like this:
 private int CastExperienceByteToInt
    {
        get => EntityUserInfoDto.YearsOfExperience;
        set => EntityUserInfoDto.YearsOfExperience = (byte)value;
    }
and using this as a variable in @bindValue option in Input Number fixs everything and make it work.

I tried adding this casting in your GenericFormField class or in the blazor but I could'nt :(, Tried the casting in the Value Object but at the end I am going to send short and do the casting in the backend but it can be solved in another way may be :)

**Comment by meziantou** [comment]
You can already do it with the current code

- Solution 1: Add another property to support binding

````
public class Sample
{        
    [System.ComponentModel.DataAnnotations.Editable(false)]
    public byte ByteValue { get; set; }

    [System.ComponentModel.DataAnnotations.Display(Name = "Byte Value")]
    public int ByteValueBindable { get => ByteValue; set => ByteValue = (byte)value; }
}
````

- Solution 2: Create a custom editor. You can find examples in the sample https://github.com/meziantou/Meziantou.Framework/blob/29ef456bddff742d7e0d037ad1947619b0a12241/Samples/BlazorAppSample/Pages/GenericFormDemo.razor#L60

**Comment by meziantou** [comment]
> If you can answer how can we add the additionalattributes

What do you mean?

**Comment by marceloruilova** [comment]
I need to add a placeholder, but it's not something we I don't know how. For adding the class it's used EditorClass and I can add the placeholder by entering the class and make use of  builder.AddAttribute(6, "placeholder", "Test placeholder");

**Comment by marceloruilova** [comment]
Should I try creating a custom editor or there is another solution that is easier?

**Comment by meziantou** [comment]
If you want to add a label or something similar, you can set `FieldTemplate`. If you want to change the editor, you need to use a custom editor.

If I think of another easier way, I'll let you know

**Comment by marceloruilova** [comment]
Thanks, I understand and I am going to create a custom Editor :)

**Comment by meziantou** [comment]
The next version will support placeholder by using the `DisplayAttribute.Prompt` property ([sample](https://github.com/meziantou/Meziantou.Framework/blob/main/Samples/BlazorAppSample/Pages/GenericFormDemo.razor#L77-L78))

```
[System.ComponentModel.DataAnnotations.Display(Prompt = "placeholder message")]
public string Property { get; set; }
```
