### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by marceloruilova** [meziantou/Meziantou.Framework#485]
Hi, I' ve been working with the placeholder but adding it with an annotation is giving problems with internationalization so can we add it on the GenericForm.razor as a parameter and adding it from there instead of an annotation?
I added it but I have .net 6 and updating it it' s not good for me, so i don' t do a pull request :)

Thanks :)

**Comment by meziantou** [comment]
I'm not sure to understand your issue. Maybe you can share some code to explain your issue.

Maybe this is related to your issue: The `DisplayAttribute` already supports localization with the `ResourceType` property.

**Comment by marceloruilova** [comment]
Sorry, I made a mistake. Don' t worry because I figured out that placeholder and @Lang.ResourceManager don' t work so I think i am going to use a label instead of placeholder, thanks for how fast you answer friend :)
