### ISSUE TITLE
Meziantou.Framework.Win32.CredentialManager is not Strong Name Signed

### ISSUE THREAD

**Issue by azchohfi** [meziantou/Meziantou.Framework#487]
It would be really helpful if Meziantou.Framework.Win32.CredentialManager was Strong Name Signed, since other libraries that need to use Strong Name Signing would be able to leverage it.
https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md

**Comment by meziantou** [comment]
I'm not an expert of strong naming. So, correct me if I'm wrong.
- Strong name is only _useful_ for .NET Framework. .NET Core doesn't use it. So, it's only benefits to _legacy apps_.
- I don't know what the impacts are of adding a strong name to an existing library. Does it break compilation or binding redirects?
- This is the first issue requesting to add a strong name, so I don't know if this is that useful

**Comment by azchohfi** [comment]
Hello Gerald.

> * Strong name is only _useful_ for .NET Framework. .NET Core doesn't use it. So, it's only benefits to _legacy apps_.

.NET Core apps still benefit from Strong Name signing, since it can still provide a unique identity validation for assemblies. It is not a security feature, but an identity one.

> * I don't know what the impacts are of adding a strong name to an existing library. Does it break compilation or binding redirects?

It will not break compilation, but it will break binding redirects, as the signature changes, and that is considered a breaking change. Still, only for .NET Framework, not .NET Core or .NET 5+.

> * This is the first issue requesting to add a strong name, so I don't know if this is that useful

The biggest issue is that if _Meziantou.Framework.*_ is **not** strong name signed, then **no other library that depends on it** can be strong name signed. It is a blocking issue in using this library. The only other solution would be including the source in my own source and recompile it, but there is the downside of maintenance.

**Comment by meziantou** [comment]
> .NET Core apps still benefit from Strong Name signing, since it can still provide a unique identity validation for assemblies. It is not a security feature, but an identity one.

Do you have a concrete example where strong-name is useful in .NET Core? I try to understand which use-case it would resolve. It is not something I had to use, so I'm curious.

https://github.com/dotnet/docs/issues/22412#issuecomment-764395520

> We saw strong naming creating many problems, and having diminishing value in .NET Core. We wanted problems with strong naming to go away in .NET Core. Ignoring strong names for binding was a part of the plan to achieve that.

https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named?WT.mc_id=DT-MVP-5003978#why-strong-name-your-assemblies

> For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.

**Comment by azchohfi** [comment]
Nowadays, it is mostly compliance. It is no longer focused on being a technical feature, but solely an identity guarantee. Unfortunately, this is a hard requirement for multiple applications, hence my ask to support it. Usually, the work to support it is minimal, but I understand your questions. Let me know how I can help.

**Comment by meziantou** [comment]
I tried to add a strong name to see the impacts on the solution
- I have to update all `InternalsVisibleTo` => not a problem
- Some projects depend on non-strong named assemblies such as `MongoDB.Bson` => compilation warnings CS8002

I think this will cause me more maintenance issues in the future than I would expect for this project. So, I'll close the issue as not planned.

The MIT license allows you to copy the code to your project as long as you copy the license file. `Meziantou.Framework.Win32.CredentialManager` doesn't evolve, so the maintenance cost on your side should be very small.

**Comment by azchohfi** [comment]
Fair enough. I completely understand.

**Comment by 0xced** [comment]
@azchohfi Have you considered using the [StrongNamer](https://github.com/dsplaisted/strongnamer) NuGet package? I think it might solve your issue by automatically strong naming assemblies that are not strong named at build time.
