### ISSUE TITLE
[StronlyTypedId]  -- [Question / Bug] Is it possible to have default values?

### ISSUE THREAD

**Issue by jeffward01** [meziantou/Meziantou.Framework#494]
Is it possible to have default values?  I noticed that `.Validate()` does not run when the constructor is empty.  For example:

# Scenerio

* I create a stronglyTypedId object
* Iin theory, the `Id`  should never allowed to be 'empty' or 0

## Example Unit Tests

**Example Type**

`````csharp

[StronglyTypedId(typeof(int))]
public readonly partial struct ProductId { }

`````

**Example Unit Tests**

````csharp
 
   // This is currently failing
    [Fact]
    public void ShouldNotBeEmpty()
    {
        var someId = new ProductId();
        
        Assert.NotEqual(Guid.Empty,someId.Value);
    }
````

# Question / Proposed Fix

When a user performs:

````csharp

var somePageNumber = new ProductId();  // Should not compile

````

This should **not** compile if the constructor is empty.  The user should be forced to provide an `int` value

````csharp

var somePageNumber = new ProductId(2);  // Should compile

````

However - now this also opens the door for adding a 'Validate' protected method that the user can implement - such as:

* The `int` must be greater than 0
* If not - throw exception

This also ventures down the path of 'Primitive' 'ValueObjects'

What is your opinion on this?

Thanks

**Comment by meziantou** [comment]
If you want to have only valid objects, you should use a class. Using a struct, you cannot prevent a user from creating an instance using `default(type)`.

You can already validate the value by implementing the ctor manually.

[StronglyTypedId(typeof(int))]
public partial class ProductId 
{ 
    public ProductId(int value)
    {
        // TODO validation

        _value = value;
    }
}

**Comment by jeffward01** [comment]
This makes sense. Thanks for pointing this out.
