### ISSUE TITLE
[Question]  [Code Style] .editorconfig question

### ISSUE THREAD

**Issue by jeffward01** [meziantou/Meziantou.Framework#495]
Hello!

I opened a pull request on a separate issue - and I had some issues with code styling:

> Check that new and updated code follows Meziantou.Framework's existing code formatting and naming standard

I used both JetBrains and Resharper - and for some reason your `.editorconfig` file was not detected by my IDE.

My standard code-style settings is a bit different than yours, for example I favor brackets (on new lines of-course) 😄  

I could not get my IDE to 'sense' your `.editorconfig` file - I know that this is not quite a `Meziantou.Framework` question - its rather a VisualStudio or Rider question - I just did not want to spend 1-2 hours on fixing this styling issue.

On my company and personal files I always use an `.editorconfig` file and had never had issues 'sensing' it before 

## Questions:

1.)  Do you know why the `.editorconfig` was not 'sensed' by Rider or VS?  Or perhaps it was 'sensed' but my global settings overrode it?

2.) Do you know what I can do to get the `.editorconfig` file to work?

----

Please don't spend much time on this as I understand that is probably not an issue with `Meziantou.Framework` `.editorconfig` file -  it is likely an issue with my configured settings.

Thanks

**Comment by meziantou** [comment]
Most of the coding style is provided by https://github.com/meziantou/Meziantou.Framework/blob/9214909057aa42ffa5f4ae4c17c6230ae6311203/Directory.Build.props#L70-L73. This package contains global editor configs. I don't know if Rider supports this feature. You should ask JetBrains directly.
