### ISSUE TITLE
Issue with migrating to versions above 1.0.22 of Meziantou.Framework.StronglyTypedId

### ISSUE THREAD

**Issue by ppiwow-apay** [meziantou/Meziantou.Framework#507]
Hi,

I have some issues while trying to update Meziantou.Framework.StronglyTypedId package to vesion above 1.0.22

.net 6

while trying to upgrade to 1.0.27 issue with Microsoft.CodeAnalysis occures:
` An instance of analyzer Meziantou.Framework.StronglyTypedId.StronglyTypedIdSourceGenerator cannot be created from \.nuget\packages\meziantou.framework.stronglytypedid\1.0.27\analyzers\dotnet\cs\Meziantou.Framework.StronglyTypedId.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified..`

Additionaly for version 1.0.26 some new warnings related to NRT enabled projects started to occures:

` Converting null literal or possible null value to non-nullable type.
  Possible null reference return.`

This is caused by code:

`OrderId value = default;` in `Read` method and returning this value.

**Comment by meziantou** [comment]
Hi,

The latest version changed the minimum required version of Roslyn. Why? StronglyTypedId is an incremental source generator. This means, Roslyn caches the generated code unless something that impacts the output changed. The previous versions of StronglyTypedId badly interact with Roslyn, so Roslyn never cached the output... To better handle this, I've updated the minimum required version to Microsoft.CodeAnalysis 4.3.0 as this version provides useful helpers to handle caching.

The latest version should reduce the CPU / RAM impact. Also, I've also take time to simplify the output code and speed up the code generation to reduce the impact of the generator in the editor (VS or Rider).

> Converting null literal or possible null value to non-nullable type. Possible null reference return

This is clearly not expected. I'll have a look at it quickly.

What is the code of the type (attribute + type declaration)?

**Comment by meziantou** [comment]
- Also, which version of Visual Studio do you use?
- Can you add `#error version` in the code and copy the error message (which include the Roslyn version)? see https://www.meziantou.net/getting-roslyn-csharp-compiler-and-language-versions.htm

**Comment by meziantou** [comment]
The latest version should fix the null value issue.

**Comment by ppiwow-apay** [comment]
Hi, It seems that installing newest net 6 sdk (v6.0.404) fix the issue with code analysis. NRT fixed too. So we can close both issues. Thanks a lot.
