### ISSUE TITLE
Different CredentialTypes and Persistances

### ISSUE THREAD

**Issue by Syberdoor** [meziantou/Meziantou.Framework#515]
Is there a reason WriteCredential is limited to CredentialType.Generic and CredentialPersistence.LocalMachine?
I would have liked to use this to store a CredentialType.DomainPassword for only the current session and from a little testing it worked well when changing directly in the source. 

Is there anything dangerous or problematic that this was not made a parameter of WriteCredential?

**Comment by meziantou** [comment]
I don't think there is a reason except I've never tested it. Maybe you can submit a PR with your changes.
