### ISSUE TITLE
Feature request : StronglyTypedId - add static implicit operator

### ISSUE THREAD

**Issue by StefH** [meziantou/Meziantou.Framework#516]
Example generate these two static implicit operators
``` c#
[StronglyTypedId(typeof(string))]
public partial struct AccountNumber
{
    public static implicit operator AccountNumber(string value) => Parse(value);

    public static implicit operator string(AccountNumber @this) => @this.Value;
}
```

**Comment by meziantou** [comment]
It's a duplicate of https://github.com/meziantou/Meziantou.Framework/issues/427. The original issue explains why these converters are not generated. Note that the issue didn't get enough feedbacks, so it was closed. Feel free to give more context if needed.

**Comment by StefH** [comment]
For my use case, I can just use this code:
``` c#
AccountNumber x = "abc";
```

Instead of having to use:
``` c#
AccountNumber x = AccountNumber.Parse("abc");
```

Can you explain why it reduces safety in this example?

**Comment by meziantou** [comment]
The main goal of `StronglyTypedId` is to avoid type confusion.

````
// Both properties are of type int but represent different concepts.
// It's easy to user them wrongly.
int projectId = 1;
int userId = 2;

// Using custom types, you can use the compiler to avoid errors
ProjectId projectId = ...;
UserId userId = ...;
// projectId == userId is invalid
````

If you add implicit converters, you open up some cases that should not be valid:

````
UserId a = default;
ProjectId b = default;

_ = a == 1; // valid, but it's arguable
_ = a == b; // valid, but it should not

[StronglyTypedId(typeof(int))]
public partial class UserId { 

    public static implicit operator int(UserId id) => id.Value;
}

[StronglyTypedId(typeof(int))]
public partial class ProjectId
{
    public static implicit operator int(ProjectId id) => id.Value;
}
````

As an analogy, let's consider `TimeSpan` which is a wrapper from a `long`. There is no implicit converter from/to long. You need to use properties or methods.

**Comment by StefH** [comment]
OK.

For my use-case I can just add these methods to the partial struct.

It would be nice if this could be automatic with `[StronglyTypedId(typeof(int), generateImplicitConverter: true)]`. But you can decide on that.

**Comment by meziantou** [comment]
I would accept a PR adding the `generateImplicitConverter` option if someone wants to contribute.
