### ISSUE TITLE
CodeOwnersParser ignores lines without members

### ISSUE THREAD

**Issue by jamesc-skyward** [meziantou/Meziantou.Framework#527]
This example is from GitHub's [documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file). 
```
# In this example, @octocat owns any file in the `/apps`
# directory in the root of your repository except for the `/apps/github`
# subdirectory, as its owners are left empty.
/apps/ @octocat
/apps/github
```
I'm not sure if this is intended or not, but `CodeOwnersParser` does not create a `CodeOwnersEntry` for lines without a member. For my use case, I'd like to get back a `CodeOwnersEntry` that indicates files with the pattern have no owner.

**Comment by meziantou** [comment]
It's a scenario that the lib doesn't support. In fact, there is no official documentation for the CODEOWNERS file. Each system (GitHub / GitLab) provides an example, and you must figure out what is supported. Also, the features evolve.

Maybe it can be supported by updating the `CodeOwnerEntry`

````c#
public struct CodeOwnerEntry
{
-    public string Member { get; }
+    public string? Member { get; }
}

public enum CodeOwnersEntryType 
{
+    None,
}
````

In the case of `/apps/github`, the `Member` property would be null and the `Type` would be `None`. What do you think?

**Comment by meziantou** [comment]
Would you want to submit a PR with the change?
