### ISSUE TITLE
Why are the generated converters private?

### ISSUE THREAD

**Issue by DirtyNative** [meziantou/Meziantou.Framework#538]
I am wondering why the generated converters are private. I need to use it in a different project for json serialization but right now I would need to implement the converter on my own. See this generated converter: 

``` csharp
partial class UserIdJsonConverter : global::System.Text.Json.Serialization.JsonConverter<UserId>
```

**Comment by meziantou** [comment]
There are private as this is the default visibility for a nested type when the visibility is not specified. You can change it to public by explicitly setting the visibility:

````c#
[StronglyTypedId(typeof(int))]
partial class UserId
{
    public partial class UserIdJsonConverter {}
}
````

Most of the time, you don't need to change the visibility, and so, it doesn't need to be public. There are some cases where you may need to change the converter to public, such as when using the [json source generator](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?WT.mc_id=DT-MVP-5003978) from another project.

Can you explain your scenario? Why does it need to be public in your case?

**Comment by DirtyNative** [comment]
My exact scenario is a gateway microservice architecture where I use strongly typed IDs for the whole backend domain. Meaning the ID classes are used across all microservices. I am facing a problem with Refit that it is not able to convert the IDs correctly in order to call the desired REST endpoint and I think I can manage to resolve this when I define the converter for Refit. I will try it out and give feedback

**Comment by meziantou** [comment]
Refit use Newtonsoft.Json or System.Text.Json. The generated code adds the following attributes 
- `System.ComponentModel.TypeConverterAttribute`
- `System.Text.Json.Serialization.JsonConverterAttribute`
- `Newtonsoft.Json.JsonConverterAttribute`

So, the serializer can use the converters (even if there are not public). If you want to use the System.Text.Json source generator, you need to make the converter internal or public.
