### ISSUE TITLE
[Feature Request] NuGet package validation as MSBuild task

### ISSUE THREAD

**Issue by MattKotsenas** [meziantou/Meziantou.Framework#561]
Hello!

I recently discovered your NuGet package validation tool via https://www.meziantou.net/ensuring-best-practices-for-nuget-packages.htm.

This tool is very helpful, however it's somewhat clunky to consume in my build process, which is driven entirely in MSBuild. Because it's only available as a dotnet tool, I either need to orchestrate it outside the build itself (like as a separate step in a YAML pipeline) or first install the tool then use an `<Exec>` task to run the validator.

Would you be open to the idea of also packaging the validator as an MSBuild target (here's one such example: https://natemcmaster.com/blog/2017/11/11/msbuild-task-with-dependencies/)?

MSBuild users could then add `PackageReference Include="Meziantou.Framework.NuGetPackageValidation.MSBuild" />`, which would include the validator as a console app and add a `.targets` file that adds a target that hooks the `Pack` target and calls the validator.

Let me know if this makes sense / is interesting / or if you have questions. Thanks so much for the tool!

**Comment by meziantou** [comment]
This is an interesting idea and there are multiple ways to implement it. You can wrap the _exe_ or the library. I'm not sure which one is the easiest to develop and maintain. 

I don't think I will implement it myself, but I'll accept PRs

**Comment by 0xced** [comment]
For my packages I add this in my csproj:

```xml
<Target Name="ValidateNuGetPackage" AfterTargets="Pack">
  <Exec Command="dotnet tool restore" />
  <Exec Command="dotnet validate package local $([MSBuild]::EnsureTrailingSlash($(PackageOutputPath)))$(PackageId).$(PackageVersion).nupkg" />
</Target>
```

Is it really worth packaging these 4 lines in a NuGet package?

**Comment by meziantou** [comment]
I like your approach! It's simple and easy to use. If there are multiple projects in the solution, you can add the target in a `Directory.Build.targets` file.

Note: To be safe you may need to quote the nupkg path
