### ISSUE TITLE
Cant read credential if program is running a windows service

### ISSUE THREAD

**Issue by M-Bulinski** [meziantou/Meziantou.Framework#569]
Nvm i got same error with another credential manager api. It seems that my windows service has not enough rights to read the credential manager

**Comment by M-Bulinski** [comment]
Nvm i got same error with another credential manager api. It seems that my windows service has not enough rights to read the credential manager

**Comment by meziantou** [comment]
I can't help on this one. It may depends on how you run the service, session isolation, etc.
