### ISSUE TITLE
StronglyTypedId Annotation not found anymore

### ISSUE THREAD

**Issue by DirtyNative** [meziantou/Meziantou.Framework#581]
I updated to the latest version (2.0.0) of Meziantou.Framework.StronglyTypedId and the [StronglyTypedId] annotation is no longer found

**Comment by meziantou** [comment]
The v2 contains a breaking change to fix https://github.com/meziantou/Meziantou.Framework/issues/565 (for all source generators in this repo).

Changes:
- The attribute is now in `Meziantou.Framework.Annotations`. I tried to reduce the breaking change by adding an implicit `using` for this namespace if the project has `<ImplicitUsings>enabled</ImplicitUsings>`.
- The `PackageReference` should be referenced like `<PackageReference Include="Meziantou.Framework.StronglyTypedId" Version="2.0.0" />`. I think this is the issue in your case.

**Comment by marioboncz** [comment]
Is there a nuget with it? This gives not results

https://www.nuget.org/packages?q=Meziantou.Framework.Annotations

**Comment by meziantou** [comment]
Nope, the library and the source generator are in the same package

**Comment by meziantou** [comment]
You only need to reference https://www.nuget.org/packages/Meziantou.Framework.StronglyTypedId

**Comment by meziantou** [comment]
Before,

````xml
<PackageReference Include="Meziantou.Framework.StronglyTypedId" Version="1.0.35">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
</PackageReference>
````

After,

````xml
<PackageReference Include="Meziantou.Framework.StronglyTypedId" Version="2.0.0" />
````

**Comment by marioboncz** [comment]
In my case it was rebuild issue (needed to remove bin/obj on some other included projects).

**Comment by DirtyNative** [comment]
Okay nice, removing the additional lines fixed that issue. Thanks a lot for that fast response!
