### ISSUE TITLE
Cannot upgrade to FastEnum 2.0

### ISSUE THREAD

**Issue by petrkoutnycz** [meziantou/Meziantou.Framework#583]
Hi there,

I am having issues when upgrading to 2.0 of FastEnum nuget. I created a repository testing it but I am unable even to build it. Is there a possibility I am doing it wrong or...? Thank you!

Repository: https://github.com/petrkoutnycz/fastenum-repro-upgrade-v2

**Comment by meziantou** [comment]
You need to update the csproj:

before:

````
<PackageReference Include="Meziantou.Framework.FastEnumToStringGenerator" Version="1.0.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
````

after:

````
<PackageReference Include="Meziantou.Framework.FastEnumToStringGenerator" Version="2.0.0" />
````

**Comment by petrkoutnycz** [comment]
I see, that is weird that Rider did not realize that 🤔

**Comment by meziantou** [comment]
My bad, the package is still defined as a dev dependency. I'll fix that soon...

**Comment by petrkoutnycz** [comment]
Okay, thanks a lot :-)
