### ISSUE TITLE
HumanReadableSnapshotSerializer DefaultIgnoreCondition ignores Default instead of null

### ISSUE THREAD

**Issue by msrouchou** [meziantou/Meziantou.Framework#587]
Hello Meziantou 👋🏻  

As the title says:

`DefaultIgnoreCondition = HumanReadableIgnoreCondition.WhenWritingDefault,`
should be 
`DefaultIgnoreCondition = HumanReadableIgnoreCondition.WhenWritingNull,`

in 

https://github.com/meziantou/Meziantou.Framework/blob/ce04729d3640bd7de3c02fd387ffe50f9c5c3bd3/src/Meziantou.Framework.InlineSnapshotTesting/Serialization/HumanReadableSnapshotSerializer.cs#L17C22-L17C22 

The observed behavior is that any `boolean` that is `false`, or `int` that is `0`, is ignored.

I can overide that in my settings of course, 

Is it by design ?

**Comment by meziantou** [comment]
It's by design. The idea is to get the minimal snapshot needed.

Feel free to update the default settings or by snapshot settings if needed.
