### ISSUE TITLE
StronglyTypedId: Add support for serialising as dictionary key (System.Text.Json)

### ISSUE THREAD

**Issue by ansteele** [meziantou/Meziantou.Framework#603]
When attempting to use a StronglyTypedId as a dictionary key, System.Text.Json will throw an exception of the form:

> The type 'Program.StrongID' is not a supported dictionary key using converter of type 'Program.StrongID+StrongIDJsonConverter'.

Which led me to this .NET issue: [Allow custom converters for dictionary keys](https://github.com/dotnet/runtime/issues/46520).

Looks like .NET added [ReadAsPropertyName](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.readaspropertyname?view=net-8.0)/[WriteAsPropertyName](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.writeaspropertyname?view=net-8.0) to solve this issue, would it be possible for the generated JsonConverter for StronglyTypedId to include these methods to allow use as dictionary keys?

Many thanks

**Comment by meziantou** [comment]
Thanks for the suggestion and the link to the .NET issue. I've made a PR and the new version should be available soon.
