### ISSUE TITLE
Suggestion: Contribute InfiniteScrolling to Blazor 

### ISSUE THREAD

**Issue by sven5** [meziantou/Meziantou.Framework#611]
Hi,

at first, thanks for your effort in this component.
Did you ever think about contributing your `InfiniteScrolling` component to the official ASP.NET Core repo? This should be a part of upcoming .NET 9.

However, there is a `Virtualize` native Blazor component but this has bugs. Currently, it cannot deal with flex layouts. 
From my perspective is your approach much better. 

Regards
Sven

**Comment by meziantou** [comment]
> Did you ever think about contributing your `InfiniteScrolling` component to the official ASP.NET Core repo

Nope, if you think this is a useful component and it should be part of the builtin component, feel free to open an issue on the ASP.NET core repository. This will improve the awareness of the team and help them prioritize the feature.

> there is a Virtualize native Blazor component

The InfiniteScrolling and Virtualize component have different usages. InfiniteScrolling doesn't provide a DOM virtualization. It only loads items lazily when the user reaches the end of the list.

> However, there is a Virtualize native Blazor component, but this has bugs. Currently, it cannot deal with flex layouts.

If there is a bug in `Virtualize`, you should open a bug into the ASP.NET Core repo.
