### ISSUE TITLE
`Get` functions for JobObject

### ISSUE THREAD

**Issue by toschlog** [meziantou/Meziantou.Framework#613]
I need to be able to read values from a job object.  For example, I need `GetCpuRateHardCap()`.  Are you open to a pull request if I add the functions I need?   CONTRIBUTING.md mentions pull requests for bug fixed, but not for new features.

Thanks.

**Comment by meziantou** [comment]
Feel free to submit a PR to add the feature!

**Comment by toschlog-sony** [comment]
I have created A [pull request](https://github.com/meziantou/Meziantou.Framework/pull/614).

My 'get' function returns a tuple containing the enabled flag and the value.  If that's not your style, I could create two separate functions.

Thanks!
