### ISSUE TITLE
ConcurrentObservableCollection for WinUI 3

### ISSUE THREAD

**Issue by ghost1372** [meziantou/Meziantou.Framework#622]
can you provide ConcurrentObservableCollection for WinUI 3?
99% codes are same and only dispatcher is diffrenet.
i tried to modify it. i can see that items added into collection but does not shown in UI/ListView.

**Comment by meziantou** [comment]
The current project doesn't have anything related to WinUI now. So, implementing this feature would also mean adding tests and maybe UI tests which may not be easy. Also, I don't have any need on WinUI. So, I don't think this is something I would like to do now.

A possibility would be to abstract the current collection and let the user define the "dispatcher" through an interface. So, you would have 2 implementations, one for WPF and one for WinUI.

> i tried to modify it. i can see that items added into collection but does not shown in UI/ListView.

Do you have more info about that? Have you tried to debug it?
