### ISSUE TITLE
Include property order into default snapshot settings

### ISSUE THREAD

**Issue by blazkovicz** [meziantou/Meziantou.Framework#649]
Default inline snapshot setup are perfectly fine except one thing: property order.

Several times we got snapshot difference on identical data when code was slightly modified without changing checked functionality.
This is so inconvenient and we had to dig into HumanReadableSnapshotSerializer setup and set there PropertyOrder setting.

Why isn't Ordinal switched on by default? It would cover majority of the cases.

package Meziantou.Framework.InlineSnapshotTesting 3.0.7

**Comment by meziantou** [comment]
Which target framework are you using? (e.g. net48, net6.0, net8.0)

**Comment by blazkovicz** [comment]
Net 8.0

**Comment by meziantou** [comment]
If I'm not mistaken, property order in .NET 8 is deterministic, based on declaration order. So, you should not have any difference when you generate snapshots. Note that this is not true for older versions of .NET (I don't remember which one introduce this change, but it's recent).

Do you have any ordering issue with .NET 8? If so, could you provide a small repro?

**Comment by blazkovicz** [comment]
I have ordering issue any time I touch related code or input test data.

For example there is an array of entities processed to another array of entities, which is checked later with snapshot. I add or change one entity. Snapshot can change property order for other sibling entities even though they were not touched. Or there was code change in input model, which was later reverted. Snapshot in test changed the order of properties in checked entity of that type. Entities are big and I save snapshots to files, it is very inconvenient to regenerate 15+ snapshots just cos of property order change.It is really easily reproduced and emerges very often. Probably relates to solution rebuild.

We solved issue by providing property sort setting, but I assure it is better to set default for inline snapshots working stably with any net version.

Net 8.0.7 is used (latest stable).

It's your choice to make changes of close the issue. I will not provide repro, sorry.

**Comment by meziantou** [comment]
I think I've found the issue. The code uses `List<T>.Sort` which is not stable. This may explain why the property order is not preserved. I'll switch to `Enumerable.Order()`.

I'll publish a fix soon. Feel free to reopen the issue if you still reproduce this issue with the new version.
