### ISSUE TITLE
HttpClientMock supporting custom content types.

### ISSUE THREAD

**Issue by bmazzarol-bunnings** [meziantou/Meziantou.Framework#654]
Hi @meziantou ,

Would it be possible to add an additional constructor to the [HttpClientMock](https://github.com/meziantou/Meziantou.Framework/blob/main/src/Meziantou.Framework.HttpClientMock/HttpClientMock.cs#L28) to pass a `WebApplicationBuilder`?

Trying to mock a post call that receives XML and I want to set `AddXmlSerializerFormatters()`.

If this is acceptable, I can raise a PR.

If you have a better way to do it, happy to consider that as well. 

Thanks mate!

**Comment by bmazzarol-bunnings** [comment]
Found a workaround https://stackoverflow.com/questions/70006903/minimal-api-and-xml-formatters

So, my exact use case does not need the change.

I still think it might be a good change in case something needs to be done before its built, if you disagree feel free to let me know and I can close this.

**Comment by meziantou** [comment]
I think you can add a new overload `public HttpClientMock(Action<WebApplicationBuilder>? configure)`. Do you want to submit a PR?
