### ISSUE TITLE
PromptForCredentials() returns null when the user enters a domain

### ISSUE THREAD

**Issue by sclarke81** [meziantou/Meziantou.Framework#8]
The logic in `GetCredentialsFromOutputBuffer()` doesn't handle domains correctly. I think there are two issues:

1. If `CredUnPackAuthenticationBuffer()` did return a domain then the outputs are set to null and false is returned.
1. If `CredUIParseUserName()` returns success the outputs are set to null and false is returned, even though a domain has been parsed.

**Comment by sclarke81** [comment]
Do you think you could push a new NuGet package with this change in it?

**Comment by meziantou** [comment]
The new package is available

**Comment by sclarke81** [comment]
Awesome, thank you!
