### ISSUE TITLE
Can't retrieve credentials when using windows service

### ISSUE THREAD

**Issue by myshon** [meziantou/Meziantou.Framework#93]
I'm creating Worker in .NET Core 3.1 for Windows Service as described here: https://dotnetcoretutorials.com/2019/12/07/creating-windows-services-in-net-core-part-3-the-net-core-worker-way 
I'm using Meziantou.Framework.Win32.CredentialManager 1.4 for API credentials in the Worker. 
            
```
var appName = "MyAppName";
var cred =  CredentialManager.ReadCredential(appName);
```
I have generic credentials defined using Control Panel\All Control Panel Items\Credential Manager. When I run worker locally then credentials are retrieved correctly. However, when I install the worker as a service
```
sc create MyAppName ...
sc start MyAppName
```
Windows service runs correctly, but CredentialManager returns the list with a single item "XboxLive" which is the last item on the list in Credential Manager UI.  The other credentials are missing. The server runs on my local account with admin rights. 

Do you have any idea why it behaves this way?

**Comment by meziantou** [comment]
I think the user that runs the service is different from the user that saved the creds. I'm not sure how to address this issue. This can be related to the [CredentialPersistence](https://github.com/meziantou/Meziantou.Framework/blob/1c134cdf6dde591c4fb34d46b7845de1101506aa/src/Meziantou.Framework.Win32.CredentialManager/CredentialPersistence.cs).

**Comment by myshon** [comment]
Confirm, I added credentials as a different user (using runas command) and changed user of the windows service. Then it started working. Thanks!
